info:
  title: Bookadzone Backend API
  description: API for managing FAQs and user authentication for the Bookadzone platform.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1/
    description: Local development server
openapi: 3.0.3
paths:
  # Authentication Endpoints
  /auth/login:
    post:
      summary: Authenticate a user or admin
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: admin@gmail.com
                password:
                  type: string
                  example: admin@123
                testField:
                  type: string
                  example: test
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Logged in successfully
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 68ad430b8089095867639823
                      email:
                        type: string
                        example: bookadzone@gmail.com
                      role:
                        type: string
                        example: super-admin
                      status:
                        type: string
                        example: active
        '400':
          description: Invalid credentials or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      summary: Refresh an authentication token
      tags:
        - Authentication
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: Bearer token for authentication
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Token refreshed successfully
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 68ad430b8089095867639823
                      email:
                        type: string
                        example: bookadzone@gmail.com
                      role:
                        type: string
                        example: super-admin
                      status:
                        type: string
                        example: active
                  expiresIn:
                    type: string
                    example: 1d
        '400':
          description: Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  # FAQ Endpoints
  /faqs:
    post:
      summary: Create a new FAQ
      tags:
        - FAQs
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaqInput'
      responses:
        '201':
          description: FAQ created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ created
                  data:
                    $ref: '#/components/schemas/Faq'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get all FAQs
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: status
          schema:
            type: string
            enum: [active, inactive]
      responses:
        '200':
          description: List of FAQs
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faq'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 1
                      active:
                        type: integer
                        example: 1
                      inactive:
                        type: integer
                        example: 0
                      totalPages:
                        type: integer
                        example: 1
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/getFaqById/{id}:
    get:
      summary: Get a FAQ by ID
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      responses:
        '200':
          description: FAQ found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/Faq'
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/updateFaq/{id}:
    put:
      summary: Update a FAQ by ID
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FaqInput'
      responses:
        '200':
          description: FAQ updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ updated
                  data:
                    $ref: '#/components/schemas/Faq'
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/softDeleteFaq/{id}:
    delete:
      summary: Soft delete a FAQ by ID
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      responses:
        '200':
          description: FAQ deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ deleted successfully
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/togglestatus/{id}:
    patch:
      summary: Toggle the status of a FAQ (active/inactive)
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      responses:
        '200':
          description: FAQ status toggled
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ status toggled
                  data:
                    $ref: '#/components/schemas/Faq'
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/trash:
    patch:
      summary: Get all trashed FAQs
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: status
          schema:
            type: string
            enum: [active, inactive]
      responses:
        '200':
          description: List of trashed FAQs
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Faq'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 1
                      active:
                        type: integer
                        example: 1
                      inactive:
                        type: integer
                        example: 0
                      totalPages:
                        type: integer
                        example: 1
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/restore/{id}:
    patch:
      summary: Restore a soft-deleted FAQ
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      responses:
        '200':
          description: FAQ restored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ restored successfully
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /faqs/permanentDelete/{id}:
    delete:
      summary: Permanently delete a FAQ
      tags:
        - FAQs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: FAQ ID
      responses:
        '200':
          description: FAQ permanently deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: FAQ permanently deleted
        '400':
          description: FAQ id is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: FAQ not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Faq:
      type: object
      properties:
        _id:
          type: string
          example: 68ad430b8089095867639823
        question:
          type: string
          example: What is the purpose of this API?
        answer:
          type: string
          example: This API manages FAQs for the Bookadzone platform.
        status:
          type: string
          enum:
            - active
            - inactive
          example: active
        isDeleted:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: 2025-09-09T12:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2025-09-09T12:00:00Z
      required:
        - question
        - answer
    FaqInput:
      type: object
      properties:
        question:
          type: string
          example: What is the purpose of this API?
        answer:
          type: string
          example: This API manages FAQs for the Bookadzone platform.
        status:
          type: string
          enum:
            - active
            - inactive
          example: active
        isDeleted:
          type: boolean
          example: false
      required:
        - question
        - answer
    Error:
      type: object
      properties:
        status:
          type: string
          example: fail
        message:
          type: string
          example: Invalid input
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
